<?php

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function monahan_variables_theme() {
  return [
    'mv_add_list' => [
      'variables' => ['content' => NULL],
    ],
  ];
}

/**
 * Prepares variables for list of available Monahan Variables Groups.
 *
 * Default template: mv-add-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: An array of MVType entities.
 */
function template_preprocess_mv_add_list(&$variables) {
  $variables['types'] = [];
  if (!empty($variables['content'])) {
    foreach ($variables['content'] as $type) {
      /** @var \Drupal\monahan_variables\MVTypeInterface $type */
      $variables['types'][$type->id()] = [
        'type' => $type->id(),
        'label' => $type->label(),
        'url' => new Url(
          'monahan_variables_mv.add',
          ['monahan_variables_mv_type' => $type->id()]
        ),
        'description' => [
          '#markup' => $type->getDescription(),
        ],
      ];
    }
  }
}
